@startuml cuarto
' view in vertical direction
left to right direction
title Sistema de Inventario del Cuarto

:Yo: as Admin

rectangle "Sistema Inventario de Mi Cuarto" {
    (Gestionar Items) as CU1
    (Gestionar Muebles) as CU2
    (Gestionar Inmuebles) as CU3
    ' (Buscar Item) as CU4
    (Gestionar Categorías) as CU5
    (Gestionar Ubicaciones) as CU6
    (Buscar Item) as CU7

    ' mueble
    (Alta Mueble) as CU2.1
    (Baja Mueble) as CU2.2
    (Modificar Mueble) as CU2.3

    ' inmueble
    (Alta Inmueble) as CU3.1
    (Baja Inmueble) as CU3.2
    (Modificar Inmueble) as CU3.3

    ' categorías
    (Alta Categoría) as CU5.1
    (Baja Categoría) as CU5.2
    (Modificar Categoría) as CU5.3

    ' ubicaciones
    (Alta Ubicación) as CU6.1
    (Baja Ubicación) as CU6.2
    (Modificar Ubicación) as CU6.3

    ' buscar item
    (Buscar Item por Criterio) as CU7.1

    CU2 .-> CU2.1 : include
    CU2 .-> CU2.2 : include
    CU2 .-> CU2.3 : include

    CU3 .-> CU3.1 : include
    CU3 .-> CU3.2 : include
    CU3 .-> CU3.3 : include

    CU5 .-> CU5.1 : include
    CU5 .-> CU5.2 : include
    CU5 .-> CU5.3 : include

    CU6 .-> CU6.1 : include
    CU6 .-> CU6.2 : include
    CU6 .-> CU6.3 : include

    CU7 .-> CU7.1 : include

    CU2 .-> CU5 : extend
    CU2 .-> CU6 : extend
    
    CU3 .-> CU5 : extend
    CU3 .-> CU6 : extend
}

CU1 --> CU2
CU1 --> CU3
' CU1 --> CU5
' CU1 --> CU6

Admin --> CU1
' Admin --> CU4
Admin --> CU7

@enduml
